### ISSUE TITLE
Change the plugin to the user group

### ISSUE THREAD

**Issue by anibalsanchez** [zero-24/plg_system_force2fausergroup#5] opened 2020-10-13 09:13 UTC
It looks like the plugin only is linked to the `onUserAfterLogin` to optimize the performance, please, change it to be a user plugin.

**Comment by zero-24** [comment] 2020-10-13 12:25
Well we have to make sure that you can not leave the edit screen without the setup of 2fa so we have to use a system event that catches that cases right?

**Comment by anibalsanchez** [comment] 2020-10-13 13:08
It depends on how strict you want to be.

You are adding the plugin to force 2FA on a certain group of users as a system plugin that executes on every page load initialization. 

I think that it is better if the checkup is only executed with it is required, avoiding the execution at the system level/ onAfterInitialise.

You could execute the checkup `onUserAfterLogin`, and combine with other conditions such us only if the user is registered or only when the user is a backend user.

**Comment by zero-24** [comment] 2020-10-17 09:30
> It depends on how strict you want to be.

Well as strict as possible as we want to force it right?

> I think that it is better if the checkup is only executed with it is required, avoiding the execution at the system level/ onAfterInitialise.

Well yes that is already happening. With the [has2fa](https://github.com/zero-24/plg_system_force2fausergroup/blob/master/force2fausergroup.php#L96) check. This does also [not run on guest users](https://github.com/zero-24/plg_system_force2fausergroup/blob/master/force2fausergroup.php#L90) and when [no 2fa plugins are enabled](https://github.com/zero-24/plg_system_force2fausergroup/blob/master/force2fausergroup.php#L114).

So I'm closing here as intended behavior for now.

**Closed as completed by zero-24** 2020-10-17 09:30 UTC
